export enum MainframeEvent {
  announceGiveaway = "announcegiveaway",
  backseat = "backseat",
  banUser = "banuser",
  chatMessage = "chatmessage",
  cheer = "cheer",
  deleteChatMessage = "deletechatmessage",
  drawGiveaway = "drawgiveaway",
  dropEmotes = "dropemotes",
  dropUser = "dropuser",
  endGiveaway = "endgiveaway",
  enterGiveaway = "entergiveaway",
  follow = "follow",
  freeze = "freeze",
  imageDrop = "imagedrop",
  merch = "merch",
  moodChange = "moodchange",
  numeronym = "numeronym",
  raid = "raid",
  shoutOut = "shoutout",
  specialUserJoin = "specialuserjoin",
  startGiveaway = "startgiveaway",
  special = "special",
  sub = "sub",
  teamMemberJoin = "teammemberjoin",
  timer = "timer",
  timeoutUser = "timeoutuser",
  theClaw = "theclaw",
  weather = "weather",
  weatherTrailEvent = "settrailing",
  yeetUser = "yeetuser",
}

export enum CurrentMoods {
  Coffee = "coffee",
  Cool = "cool",
  Dolla = "dolla",
  Fire = "fire",
  Heart = "heart",
  Hype = "hype",
  Majick = "majick",
  PewPew = "pewpew",
  Rap = "rap",
  Sad = "sad",
  Star = "star",
  Tattoo = "tattoo",
  Troll = "troll",
}
