export enum MainframeEvent {
  sub = "sub",
  dropUser = "dropuser",
  weather = "weather",
  dropEmotes = "dropemotes",
  raid = "raid",
  cheer = "cheer",
  specialUserJoin = "specialuserjoin",
  weatherTrailEvent = "settrailing",
  teamMemberJoin = "teammemberjoin",
  chatMessage = "chatmessage",
  yeetUser = "yeetuser",
  follow = "follow",
  startGiveaway = "startgiveaway",
  endGiveaway = "endgiveaway",
  enterGiveaway = "entergiveaway",
  drawGiveaway = "drawgiveaway",
  imageDrop = "imagedrop",
  moodChange = "moodchange",
}

export enum CurrentMoods {
  Cool = "cool",
  Dolla = "dolla",
  Fire = "fire",
  Heart = "heart",
  Majick = "majick",
  PewPew = "pewpew",
  Sad = "sad",
  Star = "star",
}
